specVersion: 0.2.0
name: acala-tokens
version: 1.0.0
description: 'statistics tokens data'
repository: 'https://github.com/AcalaNetwork/acala-tokens-subql'
schema: 
    file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  dictionary: https://api.subquery.network/sq/subquery/acala-dictionary
  endpoint: wss://acala.polkawallet.io
  chaintypes:
    file: './src/chain-types.js'
dataSources:
    - kind: substrate/Runtime
      startBlock: 1
      mapping:
        file: './dist/index.js'
        handlers:
          - handler: handleBalancesTransfer
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Transfer
          - handler: handleBalancesDeposit
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Deposit
          - handler: handleBalancesWithdraw
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Withdraw
          - handler: handleBalancesDustLost
            kind: substrate/EventHandler
            filter:
              module: balances
              method: DustLost
          - handler: handleBalancesReserved
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Reserved
          - handler: handleBalancesUnreserved
            kind: substrate/EventHandler
            filter:
              module: balances
              method: Unreserved
          - handler: handleBalancesReserveRepatriated
            kind: substrate/EventHandler
            filter:
              module: balances
              method: ReserveRepatriated
          - handler: handleCurrenciesTransfer
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: Transferred
          - handler: handleCurrenciesDeposite
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: Deposited
          - handler: handleCurrenciesWithdrawn
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: Withdrawn
          - handler: handleDustSwept
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: DustSwept
          - handler: handleBalanceUpdatedEvent
            kind: substrate/EventHandler
            filter:
              module: currencies
              method: BalanceUpdated
